# Generated by Django 6.0.2 on 2026-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petreport',
            name='pet',
        ),
        migrations.AddField(
            model_name='petreport',
            name='pet_breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='pet_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_report_images/'),
        ),
        migrations.AddField(
            model_name='petreport',
            name='pet_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petreport',
            name='pet_status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=20),
        ),
        migrations.AddField(
            model_name='petreport',
            name='pet_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
