# Generated by Django 6.0.2 on 2026-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 1 hour, 30 mins', max_length=50, null=True),
        ),
    ]
