# Generated by Django 6.0.2 on 2026-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuerequest',
            name='behavior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='collar_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='finder_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='is_verified_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='owner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='proof_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
