# Generated by Django 6.0.2 on 2026-05-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
