# Generated by Django 6.0.2 on 2026-04-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0002_rescuerequest_behavior_rescuerequest_collar_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescuerequest',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='collar_details',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='finder_confirmed',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='is_verified_match',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='owner_confirmed',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='proof_images',
        ),
    ]
