# Generated by Django 6.0.2 on 2026-02-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0002_pet_breed_pet_image_pet_location_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], default='User', max_length=20),
        ),
    ]
