# Generated by Django 6.0.2 on 2026-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('SuperAdmin', 'SuperAdmin'), ('ShopOwner', 'ShopOwner')], default='User', max_length=20),
        ),
    ]
