# Generated by Django 6.0.2 on 2026-04-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role_adminprofile_shopownerprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='shopownerprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_public_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='shopownerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shopownerprofile',
            name='profile_picture_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopownerprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
