# Generated by Django 6.0.2 on 2026-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_image_userprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_picture_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
