# Generated by Django 6.0.2 on 2026-04-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='status',
        ),
        migrations.AlterField(
            model_name='adoption',
            name='adopted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
