# Generated by Django 6.0.2 on 2026-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Adopted', 'Adopted'), ('Available', 'Available'), ('Lost', 'Lost'), ('Found', 'Found')], default='Available', max_length=20),
        ),
    ]
