# Generated by Django 6.0.2 on 2026-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_image_pet_image_public_id_pet_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='unique_marks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
