# Generated by Django 6.0.2 on 2026-04-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_unique_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='unique_marks',
        ),
    ]
