# Generated by Django 6.0.2 on 2026-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
