# Generated by Django 6.0.2 on 2026-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_petreport_image_public_id_petreport_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='contact_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petreport',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='found_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='last_seen_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='multiple_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='petreport',
            name='pet_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='temporary_shelter_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
