# Generated by Django 6.0.2 on 2026-04-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_petreport_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petreport',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='report_status',
        ),
    ]
