# Generated by Django 6.0.2 on 2026-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_petreport_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petreport',
            name='contact_visibility',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='found_location',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='last_seen_location',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='multiple_images',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='pet_condition',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='temporary_shelter_status',
        ),
        migrations.AddField(
            model_name='petreport',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='petreport',
            name='report_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
