# Generated by Django 6.0.2 on 2026-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Adopted', 'Adopted'), ('Available', 'Available')], default='Available', max_length=20),
        ),
    ]
