# Generated by Django 6.0.2 on 2026-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Adoption_Request', 'Adoption Request'), ('Report_Status', 'Report Status'), ('Adoption_Status', 'Adoption Status'), ('General', 'General'), ('Match_Found', 'Match Found'), ('Report_Creation', 'Report Creation'), ('Pet_Registration', 'Pet Registration')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
